[package]
name = "wasm-demo"
version = "0.1.0"
authors = ["Arkadiusz Oleksy <oleksy.arkadiusz@gmail.com>"]

[dependencies]
failure = "0.1"
serde = "1"
serde_derive = "1"
stdweb = "0.4"
yew = { git = "https://github.com/DenisKolodin/yew", features = ["toml", "yaml", "msgpack", "cbor"] }